<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rankingButton</name>
   <tag></tag>
   <elementGuidId>ed3e4404-0305-491d-a5a9-f21c39cd7787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]/div/div/div[1]/div/div/div/div/div[2]/div/div/div[1]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]/div/div/div[1]/div/div/div/div/div[2]/div/div/div[1]/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
