<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectLanguageAr</name>
   <tag></tag>
   <elementGuidId>a6119594-bf60-4551-8f4d-a252c451f913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2[contains(text(),&quot;Arabic&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2[contains(text(),&quot;Arabic&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
