<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgetPasswordTextDescription</name>
   <tag></tag>
   <elementGuidId>095e168a-965e-4880-8c81-99520c48a385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//shahid-widget[@id='shahid-widget']/div/app-forget-password/div/div/app-title/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-title-description</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>قم بالمرور على الخطوات لتعيين كلمة سر جديدة</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shahid-widget&quot;)/div[@class=&quot;shahid-widget ui-rtl&quot;]/app-forget-password[@class=&quot;ng-tns-c10-1 ng-star-inserted&quot;]/div[@class=&quot;container-shahid-widget ng-trigger ng-trigger-pageState&quot;]/div[@class=&quot;inner-container text-center&quot;]/app-title[@class=&quot;ng-tns-c10-1&quot;]/div[@class=&quot;title-container&quot;]/div[@class=&quot;main-title-description&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//shahid-widget[@id='shahid-widget']/div/app-forget-password/div/div/app-title/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='استعادة كلمة السر'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الدخول'])[1]/following::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أدخل البريد الإلكتروني الخاص بك للحصول على كلمة سر جديدة'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أرسل'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//app-title/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
