<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgetPasswordSumbitButton</name>
   <tag></tag>
   <elementGuidId>4786d6b7-2402-4b46-a2ce-446fe7d16900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//shahid-widget[@id='shahid-widget']/div/app-forget-password/div/div/div/form/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;shahid-widget&quot;]/div/app-forget-password/div/div/div/form/button/span[count(. | //*[(text() = 'أرسل' or . = 'أرسل')]) = count(//*[(text() = 'أرسل' or . = 'أرسل')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>أرسل</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;shahid-widget&quot;]/div/app-forget-password/div/div/div/form/button/span</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//shahid-widget[@id='shahid-widget']/div/app-forget-password/div/div/div/form/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أدخل البريد الإلكتروني الخاص بك للحصول على كلمة سر جديدة'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قم بالمرور على الخطوات لتعيين كلمة سر جديدة'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رجوع'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جميع الحقوق محفوظة لمجموعة © MBC Group 2018'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//button/span</value>
   </webElementXpaths>
</WebElementEntity>
