<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shareButton</name>
   <tag></tag>
   <elementGuidId>e38d26dc-4cdf-4ebc-8161-b0e7c308d08e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]//div[1]/div[2]/div[1]/div[2]/div[2]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]//div[1]/div[2]/div[1]/div[2]/div[2]//button</value>
   </webElementProperties>
</WebElementEntity>
