<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vipTagHome</name>
   <tag></tag>
   <elementGuidId>3f9a2721-bf52-4fa2-96a0-047c8a56c811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@src,'tag-vip')])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@src,'tag-vip')])[4]</value>
   </webElementProperties>
</WebElementEntity>
