<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shahidIcon</name>
   <tag></tag>
   <elementGuidId>3799eefd-1f97-4f63-95f4-7a7fedd98f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@id=&quot;shahid.net&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@id=&quot;shahid.net&quot;]</value>
   </webElementProperties>
</WebElementEntity>
