<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cardNumber</name>
   <tag></tag>
   <elementGuidId>8dc9bbc6-b278-475a-a4a4-1f6442671453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='CreditCard_cardNumberText__1VB50'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='CreditCard_cardNumberText__1VB50'])</value>
   </webElementProperties>
</WebElementEntity>
