<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vipLogo</name>
   <tag></tag>
   <elementGuidId>949da943-ab18-41fd-a0c3-ace9e7402fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[@src='https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/tag-vip-large-straight-edges.png'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[@src='https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/tag-vip-large-straight-edges.png'])</value>
   </webElementProperties>
</WebElementEntity>
