<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list</name>
   <tag></tag>
   <elementGuidId>0613c3f8-0b39-4aba-8346-1aa73e4df718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='_33OtF8lItoQOBk2POFYbGw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='_33OtF8lItoQOBk2POFYbGw']</value>
   </webElementProperties>
</WebElementEntity>
