<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>previousOperationsList</name>
   <tag></tag>
   <elementGuidId>cd124898-b4b1-4457-891a-e4d5855222b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;_33OtF8lItoQOBk2POFYbGw&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;_33OtF8lItoQOBk2POFYbGw&quot;]</value>
   </webElementProperties>
</WebElementEntity>
