<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>juniorIcon</name>
   <tag></tag>
   <elementGuidId>891d7265-c75f-4bdc-be41-42d5186db7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@src,'mena-promo-kids-logo.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(@src,'mena-promo-kids-logo.svg')]</value>
   </webElementProperties>
</WebElementEntity>
