<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>safeContentIcon</name>
   <tag></tag>
   <elementGuidId>0f7e1458-bc91-4485-8b09-e84f320bc3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(@src,'-safe-content.svg')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(@src,'-safe-content.svg')])[2]</value>
   </webElementProperties>
</WebElementEntity>
