<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>joinNowButton</name>
   <tag></tag>
   <elementGuidId>ca3f1dbf-1e68-4673-9140-92b9a57dc278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@id,'subscriptionButton')]//div)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@id,'subscriptionButton')]//div)[2]</value>
   </webElementProperties>
</WebElementEntity>
