<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProfileImg</name>
   <tag></tag>
   <elementGuidId>8ae83a63-72fa-4378-b73a-53f99b02f19a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SelectModal']/div/div[2]/div/div[2]/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staticshahid-a.akamaihd.net/mediaObject/avatar-new/adultDefault/resolutions/preview/adultDefault.png?height=200&amp;width=200&amp;croppingPoint=&amp;version=1&amp;type=png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Guest</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectModal&quot;)/div[@class=&quot;_32bcAk4KXfjcwtyrRCD3A5&quot;]/div[@class=&quot;_1zyZsEDlmPqAEi08xsQbZy&quot;]/div[@class=&quot;mniQWNIlZphWxrZhahoB0&quot;]/div[@class=&quot;IFjHv4G5xZ56svof7V-cb&quot;]/div[@class=&quot;nwmLKP8_rvjaWXO9Wui2q&quot;]/div[@class=&quot;_28MByEqaHaKicLcJCla_Vf&quot;]/div[@class=&quot;bAfacPTnsX9kNryFma-gC&quot;]/div[@class=&quot;_2t_zD34c7M2FsYitSiIASQ&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SelectModal']/div/div[2]/div/div[2]/div/div/div[2]/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Guest']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
   </webElementXpaths>
</WebElementEntity>
