<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginButton</name>
   <tag></tag>
   <elementGuidId>db8878ce-01ac-4d53-b909-3cf9b1e4604f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a//span[text()='Login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a//span[text()='Login']</value>
   </webElementProperties>
</WebElementEntity>
