<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodesTab</name>
   <tag></tag>
   <elementGuidId>fa8e2123-f4b9-4cd2-82b1-dab58f17e665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h5[contains(text(),'الحلقات')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h5[contains(text(),'الحلقات')]</value>
   </webElementProperties>
</WebElementEntity>
