<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>replayEpisode</name>
   <tag></tag>
   <elementGuidId>9a09fdbb-2e74-43c4-bc8f-1aa9d9b7ed30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'LiveMatchesTag_')]//span[text()='مُسجَّل'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'LiveMatchesTag_')]//span[text()='مُسجَّل'])[1]</value>
   </webElementProperties>
</WebElementEntity>
