<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>seasonLabel</name>
   <tag></tag>
   <elementGuidId>5098929a-0cbe-4726-89b0-bfafd3ad18d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2[contains(text(),'الموسم')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2[contains(text(),'الموسم')])[1]</value>
   </webElementProperties>
</WebElementEntity>
