<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monthsDropDownList</name>
   <tag></tag>
   <elementGuidId>7a5016b9-82fc-4457-afe2-7b5d16f6c5f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'userInformation_dropdown-list')])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'userInformation_dropdown-list')])[8]</value>
   </webElementProperties>
</WebElementEntity>
