<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sub-tryShahidVIPButton</name>
   <tag></tag>
   <elementGuidId>698b1013-976e-49ac-9b7a-a7403f7f666c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button</value>
   </webElementProperties>
</WebElementEntity>
