<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yearsDropdownList</name>
   <tag></tag>
   <elementGuidId>0ba914bd-8147-4a1c-9154-d16674f1b8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'genreBanner_plusContainer')])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'genreBanner_plusContainer')])[4]</value>
   </webElementProperties>
</WebElementEntity>
