<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchResult</name>
   <tag></tag>
   <elementGuidId>04e8013a-cde3-49b7-a8f2-b2ef5f484ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[@title=&quot;الهيبة&quot;])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[@title=&quot;الهيبة&quot;])</value>
   </webElementProperties>
</WebElementEntity>
