<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shahidOriginalFirstAsset</name>
   <tag></tag>
   <elementGuidId>d9e6e487-2bb0-41e0-a051-ca1081bdea6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class,'BundleCarousel_titleContainer_')]//following::div[contains(@class,&quot;BundleItem_posterGradient&quot;)])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'BundleCarousel_titleContainer_')]//following::div[contains(@class,&quot;BundleItem_posterGradient&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'BundleCarousel_titleContainer_')]//following::div[contains(@class,&quot;BundleItem_posterGradient&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
