<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Download</name>
   <tag></tag>
   <elementGuidId>75b1c5a7-a813-4c6a-8378-20b4b82fe7c8</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Shahid/Download.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Shahid/Download.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContainer']/div[2]/div[2]/div/div/div/div/div/div[2]/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WidgetIconHeader_icon__EpRIl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/HeaderIcons/Offline-download.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Download and watch offline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainer&quot;)/div[2]/div[@class=&quot;page-transition-enter-done&quot;]/div[@class=&quot;views_wrapper__bCSNv themeWithoutBgImage-0-2-18 themeWithoutBgImage-d1529-0-2-1577 ViewContainer_full-height__1n3L1&quot;]/div[@class=&quot;views_content__1ZjO4 views_top0__eUkUQ ViewContainer_flex__3lH7O&quot;]/div[@class=&quot;Subscription_ltr__3lD4L Subscription_fullscreen__1oMc5 Subscription_wrapper-container__1MXzX&quot;]/div[@class=&quot;shahidFont-0-2-16 shahidFont-d1443-0-2-1493 Subscription_wrapper__3wSZE&quot;]/div[@class=&quot;Subscription_animated__3pC0X Subscription_medium__1RDDU Subscription_fade-in__1Rr2S Subscription_background__3x2py&quot;]/div[@class=&quot;WidgetIconHeader_ltr__PVGzx WidgetIconHeader_logo-images-container__2pKeO shahidFont-0-2-16 shahidFont-d1443-0-2-1493&quot;]/div[@class=&quot;WidgetIconHeader_image-container__3dtGo&quot;]/img[@class=&quot;WidgetIconHeader_icon__EpRIl&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div[2]/div[2]/div/div/div/div/div/div[2]/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Download and watch offline']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
