<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>secondaryHeaderText</name>
   <tag></tag>
   <elementGuidId>837e96b8-86cc-41a5-882e-77774a4c78a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactUsForm&quot;]/div/div[1]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactUsForm&quot;]/div/div[1]/h2</value>
   </webElementProperties>
</WebElementEntity>
