<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>movieThumbnail</name>
   <tag></tag>
   <elementGuidId>6157c512-9379-4be3-8332-c55126cbdd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='/ar/movies/Just-Call-Me-Martina/movie-273923'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='/ar/movies/Just-Call-Me-Martina/movie-273923'])</value>
   </webElementProperties>
</WebElementEntity>
