<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>movieMetaData</name>
   <tag></tag>
   <elementGuidId>1fa4f91a-b26d-4e82-aaf2-34d3eda64d1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@href='/ar/movies/Just-Call-Me-Martina/movie-273923'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@href='/ar/movies/Just-Call-Me-Martina/movie-273923'])</value>
   </webElementProperties>
</WebElementEntity>
