<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list</name>
   <tag></tag>
   <elementGuidId>0186c593-c17b-4e89-8ad8-b9ed3652c0cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='_33OtF8lItoQOBk2POFYbGw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='_33OtF8lItoQOBk2POFYbGw']</value>
   </webElementProperties>
</WebElementEntity>
