<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListItems</name>
   <tag></tag>
   <elementGuidId>90658acd-92fb-47d0-b54e-c464131849b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class='_1ndiA-3Gch8J8-Ww4Sw9Zg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//li[@class='_1ndiA-3Gch8J8-Ww4Sw9Zg'])[1]</value>
   </webElementProperties>
</WebElementEntity>
