<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vipTagHome</name>
   <tag></tag>
   <elementGuidId>0aced14c-c2f2-460e-bcbf-6e96404aa8a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@src,'tag-vip')])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@src,'tag-vip')])[4]</value>
   </webElementProperties>
</WebElementEntity>
