<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainShowPoster</name>
   <tag></tag>
   <elementGuidId>94a8a49b-e4a0-419f-8dc8-34eba1cbb4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]//div[2]//a[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]//div[2]//a[1]/img</value>
   </webElementProperties>
</WebElementEntity>
