<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addToFavIcon</name>
   <tag></tag>
   <elementGuidId>3572fea6-2520-4890-8a32-2c5b3e417a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(@class,&quot;MediaItemButtons_icon&quot;)])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(@class,&quot;MediaItemButtons_icon&quot;)])[2]</value>
   </webElementProperties>
</WebElementEntity>
