<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstItemOfCarousel</name>
   <tag></tag>
   <elementGuidId>df2633ce-c1ac-4e1a-a00d-813c65f93a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//div[contains(@class,&quot;Slider_slider__container&quot;)])[6]//div[1])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[contains(@class,&quot;Slider_slider__container&quot;)])[6]//div[1])[1]</value>
   </webElementProperties>
</WebElementEntity>
