<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expirationYear</name>
   <tag></tag>
   <elementGuidId>76ce5b7b-9fd1-44bc-aff7-00c61ae7cfcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//select[@id='ExpirationYear-input-0'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//select[@id='ExpirationYear-input-0'])</value>
   </webElementProperties>
</WebElementEntity>
