<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>annualCCIcon</name>
   <tag></tag>
   <elementGuidId>89f95e9f-a505-4d03-9356-b4cf91f5e95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-classname=&quot;logo-payment-description&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-classname=&quot;logo-payment-description&quot;])[3]</value>
   </webElementProperties>
</WebElementEntity>
