<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monthlyCCIcon</name>
   <tag></tag>
   <elementGuidId>6b730347-2d83-4e63-b529-93a8a62e6edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-classname=&quot;logo-payment-description&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-classname=&quot;logo-payment-description&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
