<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>(//div[@class='_26nmETSoDyF7gR-5cZ3dXe'])[3]</description>
   <name>weeklyPackageGrid</name>
   <tag></tag>
   <elementGuidId>1035d480-a3a3-4bd2-8a30-f4e86f67d29a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-classname=&quot;content-white-box&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-classname=&quot;content-white-box&quot;])[3]</value>
   </webElementProperties>
</WebElementEntity>
