<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>weeklyNetworkOperatorIcon</name>
   <tag></tag>
   <elementGuidId>22b71066-f4f1-402e-86ca-609f3d2befb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-classname=&quot;logo-payment-description&quot;])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-classname=&quot;logo-payment-description&quot;])[4]</value>
   </webElementProperties>
</WebElementEntity>
