<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>weeklyNetworkOperatorButton</name>
   <tag></tag>
   <elementGuidId>52755250-9c7c-4f63-b51e-cf3df7e6a477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@data-classname=&quot;payment-button-wrap&quot;])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-classname=&quot;payment-button-wrap&quot;])[4]</value>
   </webElementProperties>
</WebElementEntity>
