<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addProfileAvatar</name>
   <tag></tag>
   <elementGuidId>3e5f2f24-a99c-441d-973d-6bd93db9fe54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;AvatarBox_profile-edit-icon&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;AvatarBox_profile-edit-icon&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
