<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lifestyle</name>
   <tag></tag>
   <elementGuidId>ccd2923c-ea3d-408c-ba62-ab1c5933de0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/shows/أسلوب-الحياة?genre=7867')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/shows/أسلوب-الحياة?genre=7867')]</value>
   </webElementProperties>
</WebElementEntity>
