<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cardNumber</name>
   <tag></tag>
   <elementGuidId>c7056155-7a99-4f05-8a70-3fcb7cb2bc03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='CreditCard_cardNumberText__1VB50'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='CreditCard_cardNumberText__1VB50'])</value>
   </webElementProperties>
</WebElementEntity>
