<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yourNextPaymentText</name>
   <tag></tag>
   <elementGuidId>ade77e81-31f8-409d-a6a7-e9225fbe4f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//p[@class='Settings_pre-text'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//p[@class='Settings_pre-text'])</value>
   </webElementProperties>
</WebElementEntity>
