<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foxDrama</name>
   <tag></tag>
   <elementGuidId>f1811be1-07d8-4f64-9d72-d6e1e8f84732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/series/Fox-Drama?genre=9785')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/series/Fox-Drama?genre=9785')]</value>
   </webElementProperties>
</WebElementEntity>
