<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addEmailDescription</name>
   <tag></tag>
   <elementGuidId>f5a49753-9a5f-404f-8042-757d7fefca51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'userInformation_linkEmailDisclamer__')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'userInformation_linkEmailDisclamer__')]</value>
   </webElementProperties>
</WebElementEntity>
