<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>genderDropDownButton</name>
   <tag></tag>
   <elementGuidId>32a1a65a-18c7-423f-ade7-8b2b04c16b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'userInformation_dropdown__2va_T')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'userInformation_dropdown__2va_T')])[1]</value>
   </webElementProperties>
</WebElementEntity>
