<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foxCinema</name>
   <tag></tag>
   <elementGuidId>4c6c44d4-afb2-4e79-8b7a-d79ec50edb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/movies/Fox-Cinema?genre=9787')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/movies/Fox-Cinema?genre=9787')]</value>
   </webElementProperties>
</WebElementEntity>
