<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AllChannels</name>
   <tag></tag>
   <elementGuidId>1c803958-cf59-43b2-aa18-f65677ec5794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'PlayerPlaylistItem_imageContainer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'PlayerPlaylistItem_imageContainer')]</value>
   </webElementProperties>
</WebElementEntity>
