<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Movies</name>
   <tag></tag>
   <elementGuidId>c8ff70eb-904e-493c-bbee-1bd3d3a66409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[contains(@resource-id,'content_menu')]/android.widget.TextView[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[contains(@resource-id,'content_menu')]/android.widget.TextView[2]</value>
   </webElementProperties>
</WebElementEntity>
