<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sports</name>
   <tag></tag>
   <elementGuidId>f3a26b03-c137-4e2a-ad67-f4e039560863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[contains(@resource-id,'content_menu')]/android.widget.TextView[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[contains(@resource-id,'content_menu')]/android.widget.TextView[3]</value>
   </webElementProperties>
</WebElementEntity>
