<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>applicationsFooter</name>
   <tag></tag>
   <elementGuidId>96c89143-32ba-4019-92b6-719c928ce8cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li//h2[contains(text(),'Applications')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li//h2[contains(text(),'Applications')]</value>
   </webElementProperties>
</WebElementEntity>
