<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReactivateSubscriptionButton</name>
   <tag></tag>
   <elementGuidId>66555b3f-f32e-4e01-b759-4687549e34ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[contains(@class,'Button_btn-submit-ready')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[contains(@class,'Button_btn-submit-ready')])[2]</value>
   </webElementProperties>
</WebElementEntity>
