<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>creditCardInfo</name>
   <tag></tag>
   <elementGuidId>7abc4547-c2a4-47a9-b845-f6e8d74b5628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;CreditCard_cardInfoContainer__&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;CreditCard_cardInfoContainer__&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
