<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscriptionStatus</name>
   <tag></tag>
   <elementGuidId>b6ac31b6-2b02-4fad-a695-019ad3345b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;ManageSubscriptionInfo_subscription-status&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;ManageSubscriptionInfo_subscription-status&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
