<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>viewTransactionsHistoryButton</name>
   <tag></tag>
   <elementGuidId>3949a0f8-c613-4253-a287-ba4058a3a34b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,&quot;ManageSubscriptionInfo_arrow-button__&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,&quot;ManageSubscriptionInfo_arrow-button__&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
