<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>applicationsFooter</name>
   <tag></tag>
   <elementGuidId>2522d3d2-7bf5-4da2-8a01-7f645b817e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,&quot;/applications&quot;)]//h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,&quot;/applications&quot;)]//h2</value>
   </webElementProperties>
</WebElementEntity>
