<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contactUsFooter</name>
   <tag></tag>
   <elementGuidId>70fb76e7-b6d6-49ac-a4c3-06ea809286d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,&quot;/contact-us&quot;)]//h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,&quot;/contact-us&quot;)]//h2</value>
   </webElementProperties>
</WebElementEntity>
