<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>latestNewsFooter</name>
   <tag></tag>
   <elementGuidId>ccc8ba63-ee07-44f0-970d-aa58b1cf0fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/blog.shahid.mbc.net')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/blog.shahid.mbc.net')]</value>
   </webElementProperties>
</WebElementEntity>
