<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noFeatureAvaiableText</name>
   <tag></tag>
   <elementGuidId>2b1597b8-32f3-4e0b-95b1-8d63f7534e05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'offers_emptyOffersTitle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'offers_emptyOffersTitle')]</value>
   </webElementProperties>
</WebElementEntity>
