<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <elementGuidId>0ae9fe44-46b2-4759-845e-db2ab97d4b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a//span[text()='Login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a//span[text()='Login']</value>
   </webElementProperties>
</WebElementEntity>
