<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThankYou</name>
   <tag></tag>
   <elementGuidId>de1d8565-3cf3-46ab-a639-f1c41befb845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[contains(@class,&quot;sadLogo_thank-you-main&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[contains(@class,&quot;sadLogo_thank-you-main&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
