<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clipThumbnail</name>
   <tag></tag>
   <elementGuidId>1a7d4d2b-da5e-4b39-b9fc-4eab7d456ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]/div/div/div[1]//div[3]//div[3]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]/div/div/div[1]//div[3]//div[3]//a</value>
   </webElementProperties>
</WebElementEntity>
