<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrongCouponCodeErrorMessage</name>
   <tag></tag>
   <elementGuidId>d85b3472-fc69-4295-81c2-3a3a041358e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='container-shahid-widget'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='container-shahid-widget'])</value>
   </webElementProperties>
</WebElementEntity>
