<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>movieMetaData</name>
   <tag></tag>
   <elementGuidId>6550416c-b7be-4a50-8a42-4ea7d7f977e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@class='_32eSlEQKPmbEzUzVhFjZaE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@class='_32eSlEQKPmbEzUzVhFjZaE']</value>
   </webElementProperties>
</WebElementEntity>
