<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noFreeEpisodesMsg</name>
   <tag></tag>
   <elementGuidId>96ed7c19-8c28-414b-be2c-9923cfe0fe08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'GridRow_no-avod-content')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'GridRow_no-avod-content')]</value>
   </webElementProperties>
</WebElementEntity>
