<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>testtt</name>
   <tag></tag>
   <elementGuidId>35cf38f6-2944-429d-b9cc-6876a9a8e1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'GridRow_no-avod-content__2cat5')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'GridRow_no-avod-content__2cat5')]</value>
   </webElementProperties>
</WebElementEntity>
