<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>favoriteButton</name>
   <tag></tag>
   <elementGuidId>aa78745e-e622-4b52-bc6d-d7d83c911414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class=&quot;xrRj-FMmAfD_QV8vXuqhH&quot;])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class=&quot;xrRj-FMmAfD_QV8vXuqhH&quot;])[10]</value>
   </webElementProperties>
</WebElementEntity>
