<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainPageLink</name>
   <tag></tag>
   <elementGuidId>8a7ff3b6-611c-47fc-ae74-4551cb9398f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@href,&quot;/home&quot;)])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@href,&quot;/home&quot;)])[2]</value>
   </webElementProperties>
</WebElementEntity>
