<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailIcon</name>
   <tag></tag>
   <elementGuidId>d6557fc6-9e64-472e-b98b-eb816e0541b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src,'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTAgMGg0OHY0OEgweiIvPgogICAgICAgIDxwYXRoIGZpbGw9IiM4NTk1QUQiIGQ9Ik00MSA5YTMgMyAwIDAgMSAzIDN2MjRhMyAzIDAgMCAxLTMgM0g3YTMgMyAwIDAgMS0zLTNWMTJhMyAzIDAgMCAxIDMtM3ptMSA4LjQ2M0wyNS4xNzEgMjkuNjIxYTIgMiAwIDAgMS0yLjM0MiAwTDYgMTcuNDY0VjM2YTEgMSAwIDAgMCAuODgzLjk5M0w3IDM3aDM0YTEgMSAwIDAgMCAxLTFWMTcuNDYzek00MSAxMUg3bC0uMTE3LjAwN0ExIDEgMCAwIDAgNiAxMnYyLjk5NkwyNCAyOGwxOC0xMy4wMDRWMTJsLS4wMDctLjExN0ExIDEgMCAwIDAgNDEgMTF6Ii8+CiAgICA8L2c+Cjwvc3ZnPgo=')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@src,'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTAgMGg0OHY0OEgweiIvPgogICAgICAgIDxwYXRoIGZpbGw9IiM4NTk1QUQiIGQ9Ik00MSA5YTMgMyAwIDAgMSAzIDN2MjRhMyAzIDAgMCAxLTMgM0g3YTMgMyAwIDAgMS0zLTNWMTJhMyAzIDAgMCAxIDMtM3ptMSA4LjQ2M0wyNS4xNzEgMjkuNjIxYTIgMiAwIDAgMS0yLjM0MiAwTDYgMTcuNDY0VjM2YTEgMSAwIDAgMCAuODgzLjk5M0w3IDM3aDM0YTEgMSAwIDAgMCAxLTFWMTcuNDYzek00MSAxMUg3bC0uMTE3LjAwN0ExIDEgMCAwIDAgNiAxMnYyLjk5NkwyNCAyOGwxOC0xMy4wMDRWMTJsLS4wMDctLjExN0ExIDEgMCAwIDAgNDEgMTF6Ii8+CiAgICA8L2c+Cjwvc3ZnPgo=')]</value>
   </webElementProperties>
</WebElementEntity>
