<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otherInquiriesTitleText</name>
   <tag></tag>
   <elementGuidId>ee7081ae-2a04-4b46-b128-b4679b200c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'SubscriptionFeatures_Title_')])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'SubscriptionFeatures_Title_')])</value>
   </webElementProperties>
</WebElementEntity>
