<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>offersList</name>
   <tag></tag>
   <elementGuidId>2eb69b88-00ab-4fc4-9b9d-04d921334ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;unorder-list&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;unorder-list&quot;]</value>
   </webElementProperties>
</WebElementEntity>
