<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeThumbnail</name>
   <tag></tag>
   <elementGuidId>159214a6-e3e6-4ce6-a9bf-66d5ba584573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[3]</value>
   </webElementProperties>
</WebElementEntity>
