<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>needHelpButton</name>
   <tag></tag>
   <elementGuidId>9283f43b-d5d5-4916-81a3-14b7a447e595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;ManageSubscriptionInfo_helpArrowButton__&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;ManageSubscriptionInfo_helpArrowButton__&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
