<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscriptionInfoMainTitle</name>
   <tag></tag>
   <elementGuidId>20abde56-0c14-4f09-b230-771e20cf58fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;ManageSubscriptionInfo_main-title__&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;ManageSubscriptionInfo_main-title__&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
