<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscriptionStatus</name>
   <tag></tag>
   <elementGuidId>46225a2d-51e7-4bbe-9520-43ee8e9617ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;ManageSubscriptionInfo_subscription-status&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;ManageSubscriptionInfo_subscription-status&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
