<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myListLink</name>
   <tag></tag>
   <elementGuidId>03734a45-8916-4f50-b3c0-eda78d9ce769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='_1ZBFue7VModJTCOy5_yAOu'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='_1ZBFue7VModJTCOy5_yAOu'])[7]</value>
   </webElementProperties>
</WebElementEntity>
