<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>changePasswordDescriptionText</name>
   <tag></tag>
   <elementGuidId>e018ed52-f9be-483a-a4d1-2a8e5fbf252b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'changePassword_changepwd-subtitle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'changePassword_changepwd-subtitle')]</value>
   </webElementProperties>
</WebElementEntity>
