<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yourNextPaymentText</name>
   <tag></tag>
   <elementGuidId>4f91999a-412a-46d6-b1fd-1876c08786d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//p[@class='Settings_pre-text'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//p[@class='Settings_pre-text'])</value>
   </webElementProperties>
</WebElementEntity>
