<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>showMetaData2</name>
   <tag></tag>
   <elementGuidId>22136032-48ba-4da2-872f-c602f361a04e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]/div/div/div[1]/div/div/div/div/div[2]/div[1]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]/div/div/div[1]/div/div/div/div/div[2]/div[1]/div[2]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
