<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>desktopUpsellPlayer_upsellImg</name>
   <tag></tag>
   <elementGuidId>7b10bb0c-0d5b-4eaa-aa83-49f195ace98d</elementGuidId>
   <imagePath>Screenshots/Targets/desktopUpsellPlayer_upsellImg.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.desktopUpsellPlayer_upsellImg__1Mvk7</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/desktopUpsellPlayer_upsellImg.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='upsell-container']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shahidstatic4.akamaized.net/mediaObject/shahid_upsell/SHAHID_VIP/ar/upsell_web_landscape/original/upsell_web_landscape.jpg?height=&amp;width=1920&amp;croppingPoint=&amp;type=webp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktopUpsellPlayer_upsellImg__1Mvk7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upsell-container&quot;)/div[@class=&quot;desktopUpsellPlayer_container__3dwPf&quot;]/div[@class=&quot;desktopUpsellPlayer_upsellImageContainer__Ai5wY&quot;]/img[@class=&quot;desktopUpsellPlayer_upsellImg__1Mvk7&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upsell-container']/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shahidstatic4.akamaized.net/mediaObject/shahid_upsell/SHAHID_VIP/ar/upsell_web_landscape/original/upsell_web_landscape.jpg?height=&amp;width=1920&amp;croppingPoint=&amp;type=webp')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
