<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>offlineDownloadIcon</name>
   <tag></tag>
   <elementGuidId>c871654b-5f45-46e0-9dfd-6f9f7e72a9c5</elementGuidId>
   <imagePath>Screenshots/Targets/Page_  -  1,  1 - Shahid.net/img_ HD_desktopUpsellPlayer_icon__gvvNl.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_  -  1,  1 - Shahid.net/img_ HD_desktopUpsellPlayer_icon__gvvNl.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='upsell-container']/div/div[2]/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktopUpsellPlayer_icon__gvvNl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/HeaderIcons/Offline-download.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>مشاهدة أوفلاين </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upsell-container&quot;)/div[@class=&quot;desktopUpsellPlayer_container__3dwPf&quot;]/div[@class=&quot;desktopUpsellPlayer_contentContainer__EKzHG&quot;]/div[@class=&quot;desktopUpsellPlayer_iconsContainer__2ysWB&quot;]/div[@class=&quot;desktopUpsellPlayer_iconWrapper__1aj0V&quot;]/img[@class=&quot;desktopUpsellPlayer_icon__gvvNl&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upsell-container']/div/div[2]/div/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='مشاهدة أوفلاين ']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
