<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>watchOnTVIcon</name>
   <tag></tag>
   <elementGuidId>fcdba5fe-da2f-4e06-96db-6701f4a31d3a</elementGuidId>
   <imagePath>Screenshots/Targets/Page_  -  1,  1 - Shahid.net/watchOnTVIcon.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.desktopUpsellPlayer_iconWrapper__1aj0V.desktopUpsellPlayer_noMargin__2JaFu > img.desktopUpsellPlayer_icon__gvvNl</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_  -  1,  1 - Shahid.net/watchOnTVIcon.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='upsell-container']/div/div[2]/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktopUpsellPlayer_icon__gvvNl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/WatchOnTV.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>تابع على شاشة التلفزيون </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upsell-container&quot;)/div[@class=&quot;desktopUpsellPlayer_container__3dwPf&quot;]/div[@class=&quot;desktopUpsellPlayer_contentContainer__EKzHG&quot;]/div[@class=&quot;desktopUpsellPlayer_iconsContainer__2ysWB&quot;]/div[@class=&quot;desktopUpsellPlayer_iconWrapper__1aj0V desktopUpsellPlayer_noMargin__2JaFu&quot;]/img[@class=&quot;desktopUpsellPlayer_icon__gvvNl&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upsell-container']/div/div[2]/div/div[3]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='تابع على شاشة التلفزيون ']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
   </webElementXpaths>
</WebElementEntity>
