<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>descriptionMoreInfo</name>
   <tag></tag>
   <elementGuidId>c9603a05-1472-4fc4-9932-77bb6b1bc673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2[@id='description-inner'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2[@id='description-inner'])[2]</value>
   </webElementProperties>
</WebElementEntity>
