<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleText</name>
   <tag></tag>
   <elementGuidId>251d7e6a-2de3-4c1e-a5fd-28a991d74f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;htmlContaner&quot;]/div/section[2]/div/div/h3/[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;htmlContaner&quot;]/div/section[2]/div/div/h3</value>
   </webElementProperties>
</WebElementEntity>
