<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeNumber2</name>
   <tag></tag>
   <elementGuidId>f5b895bc-ce13-41d8-97d1-310f20229466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@class,'PlayerPlaylistItem')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@class,'PlayerPlaylistItem')])[2]</value>
   </webElementProperties>
</WebElementEntity>
