<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addProfileAvatar</name>
   <tag></tag>
   <elementGuidId>5773dfaa-c4d0-4592-8456-8674f72d0571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;AvatarBox_profile-edit-icon&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;AvatarBox_profile-edit-icon&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
