<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adultDefault</name>
   <tag></tag>
   <elementGuidId>84246270-2ef7-410e-b56b-79bfaa252ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'AvatarBox')]//following::img[contains(@src,'avatar')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'AvatarBox')]//following::img[contains(@src,'avatar')])[1]</value>
   </webElementProperties>
</WebElementEntity>
