<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>footerUL</name>
   <tag></tag>
   <elementGuidId>9c30ed5e-c0e1-4a02-b3c3-2d0606aff991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[contains(@class,'FooterMenu_footer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[contains(@class,'FooterMenu_footer')]</value>
   </webElementProperties>
</WebElementEntity>
