<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframePOPup</name>
   <tag></tag>
   <elementGuidId>612a37cf-86f3-484c-b7c1-c4c292d483d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id=&quot;wiz-iframe-intent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@id=&quot;wiz-iframe-intent&quot;]</value>
   </webElementProperties>
</WebElementEntity>
