<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image</name>
   <tag></tag>
   <elementGuidId>f7524260-120b-4374-a54c-8a2238c648a4</elementGuidId>
   <imagePath>../../../Downloads/shahidVIP.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../../Downloads/shahidVIP.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
