<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobilyPartnerHeaderLogo</name>
   <tag></tag>
   <elementGuidId>871e756b-81f8-48fe-90bd-54964fb26ab0</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Shahid/img__PartnerHeader_logo___HYVA.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.PartnerHeader_logo___HYVA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContainer']/div[2]/div[2]/div/div/div/div[2]/section[2]/div/img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Shahid/img__PartnerHeader_logo___HYVA.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PartnerHeader_logo___HYVA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>partner-logo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/MobilyLogo.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContainer&quot;)/div[2]/div[@class=&quot;page-transition-enter-done&quot;]/div[@class=&quot;views_wrapper__bCSNv themeWithoutBgImage-0-2-18 themeWithoutBgImage-d101-0-2-183 ViewContainer_full-height__1n3L1&quot;]/div[@class=&quot;views_content-widget__1CLMB ViewContainer_flex__3lH7O&quot;]/div[@class=&quot;NewDealLandingPage_deal-landing-page__1oOcV NewDealLandingPage_animated__1i5qI NewDealLandingPage_fast__1QrD4 NewDealLandingPage_deal-landing-fade-in__2uqyR&quot;]/div[@class=&quot;NewDealLandingPage_main-container__HotRG&quot;]/section[@class=&quot;NewDealLandingPage_content-section__sjRx_&quot;]/div[@class=&quot;PartnerHeader_header__1-bEZ&quot;]/img[@class=&quot;PartnerHeader_logo___HYVA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContainer']/div[2]/div[2]/div/div/div/div[2]/section[2]/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='partner-logo']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
   </webElementXpaths>
</WebElementEntity>
