<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>posterTitle</name>
   <tag></tag>
   <elementGuidId>484ca513-4af7-499a-801d-4a2ba9b27f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@class,'PortraitItem_thumbnail__')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@class,'PortraitItem_thumbnail__')])[1]</value>
   </webElementProperties>
</WebElementEntity>
