<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VIPlogo</name>
   <tag></tag>
   <elementGuidId>d563b85c-4078-4e7c-9258-ae5ffd4cc19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@class,&quot;linkedLogo_vipLogo__&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@class,&quot;linkedLogo_vipLogo__&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
