<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstPoster</name>
   <tag></tag>
   <elementGuidId>70f78f32-281d-470d-a350-a29d5d4be238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,&quot;LandscapeItem&quot;)]//following::div[contains(@class,'ImageTemplate')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,&quot;LandscapeItem&quot;)]//following::div[contains(@class,'ImageTemplate')])[1]</value>
   </webElementProperties>
</WebElementEntity>
