<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heroBannerSwip</name>
   <tag></tag>
   <elementGuidId>f2c71c24-03cf-46a3-8288-85fb9aa58a40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@class,'logoShowPage_title')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@class,'logoShowPage_title')])[1]</value>
   </webElementProperties>
</WebElementEntity>
