<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sportPoster</name>
   <tag></tag>
   <elementGuidId>6ff9f9fa-9868-4cce-854c-877b5990a6dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@class,'PortraitItem_thumbnail')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@class,'PortraitItem_thumbnail')])[1]</value>
   </webElementProperties>
</WebElementEntity>
