<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeThumbnail</name>
   <tag></tag>
   <elementGuidId>c8159ab5-1480-4962-a85f-6a225fdba1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[3]</value>
   </webElementProperties>
</WebElementEntity>
