<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeTitle</name>
   <tag></tag>
   <elementGuidId>9920728e-c9a5-4661-876d-b89b32e424c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h1[@class='_3HCf9x5hsOGEvHt8fhHmac'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h1[@class='_3HCf9x5hsOGEvHt8fhHmac'])[3]</value>
   </webElementProperties>
</WebElementEntity>
