<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unmuteButton</name>
   <tag></tag>
   <elementGuidId>e3550193-cd83-44ce-8698-90c6f2329bdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//button[@type='button'])[3]//span[text()='Unmute'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//button[@type='button'])[3]//span[text()='Unmute'])[1]</value>
   </webElementProperties>
</WebElementEntity>
