<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hisenseTVImage</name>
   <tag></tag>
   <elementGuidId>9d0a5abc-1339-43ba-9aa8-95b9f74996b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src=&quot;https://static.s3.shahid.mbc.net/promo-pages/promos/hisense/img/bitmap.png&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src=&quot;https://static.s3.shahid.mbc.net/promo-pages/promos/hisense/img/bitmap.png&quot;]</value>
   </webElementProperties>
</WebElementEntity>
