<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>secondElementSearch</name>
   <tag></tag>
   <elementGuidId>1b529d27-1bde-4e6b-bef3-1aa578ba2764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,&quot;LandscapeItem_thumbnail&quot;)])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,&quot;LandscapeItem_thumbnail&quot;)])[2]</value>
   </webElementProperties>
</WebElementEntity>
