<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShowTitle</name>
   <tag></tag>
   <elementGuidId>f1670791-861c-43ae-9876-7235bbecd9c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@class='_2Q8UFmGhGYQWHXsTC-QSi8'])[23]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@class='_2Q8UFmGhGYQWHXsTC-QSi8'])[23]</value>
   </webElementProperties>
</WebElementEntity>
