<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assetDescription</name>
   <tag></tag>
   <elementGuidId>3de9645c-045b-4794-8926-57b35b29f31c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'MediaItem_continueWatchingLabel__')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'MediaItem_continueWatchingLabel__')])[1]</value>
   </webElementProperties>
</WebElementEntity>
