<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deviceInfoContainer</name>
   <tag></tag>
   <elementGuidId>c9ed291b-ad6a-41d8-a10e-9f9f6aaa1950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;deviceManagement_device-info-container&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;deviceManagement_device-info-container&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
