<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>news</name>
   <tag></tag>
   <elementGuidId>02dcdd1e-2d8b-4d2b-924d-6658880a5391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/shows/اخباري?genre=7861')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/shows/اخباري?genre=7861')]</value>
   </webElementProperties>
</WebElementEntity>
