<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saudi</name>
   <tag></tag>
   <elementGuidId>3bf9c578-f5c4-46f0-a9c6-29547a96ae24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/shows/سعودي?dialect=8147')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/shows/سعودي?dialect=8147')]</value>
   </webElementProperties>
</WebElementEntity>
