<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <elementGuidId>86e46d58-8d48-48fd-80a0-23e0c45aec4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a//span[text()='Connectez-vous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a//span[text()='Connectez-vous']</value>
   </webElementProperties>
</WebElementEntity>
