<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailDetailsText</name>
   <tag></tag>
   <elementGuidId>9f6bbbd5-ac90-475e-aa60-7e2cf9550c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'_2LH5qRfZbys2s_8jtL6uD3')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'_2LH5qRfZbys2s_8jtL6uD3')])[1]</value>
   </webElementProperties>
</WebElementEntity>
