<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailIcon</name>
   <tag></tag>
   <elementGuidId>5bd543ee-f812-456c-b3dc-0e26ffccd7fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'_2fu--mctlKKWccr0vDPBOq')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'_2fu--mctlKKWccr0vDPBOq')])[1]</value>
   </webElementProperties>
</WebElementEntity>
