<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>whatsappContactUSText</name>
   <tag></tag>
   <elementGuidId>57ed77b9-a298-4a2f-9207-ea57ab5aeac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'_2LH5qRfZbys2s_8jtL6uD3')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'_2LH5qRfZbys2s_8jtL6uD3')])[2]</value>
   </webElementProperties>
</WebElementEntity>
