<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendButton</name>
   <tag></tag>
   <elementGuidId>de65de01-14ac-4fcd-b40d-6d20b9189446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button//span[text()='Envoyer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button//span[text()='Envoyer']</value>
   </webElementProperties>
</WebElementEntity>
