<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accepttoReceivePromotionsandNewsText</name>
   <tag></tag>
   <elementGuidId>fc66d69b-efc3-4768-95a3-b9c5c3157a2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//label)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label)[2]</value>
   </webElementProperties>
</WebElementEntity>
