<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsAndConditionsText</name>
   <tag></tag>
   <elementGuidId>4bd70442-070e-47af-901c-f3b63cb29923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//label)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label)[1]</value>
   </webElementProperties>
</WebElementEntity>
