<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tryShahidVIPButton</name>
   <tag></tag>
   <elementGuidId>4c5edb07-daa3-48eb-b7b6-0559ccc1d4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@id='subscribe_button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@id='subscribe_button'])[3]</value>
   </webElementProperties>
</WebElementEntity>
