<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myListLink</name>
   <tag></tag>
   <elementGuidId>aaa207c3-b42e-4ed8-995f-8202d998a046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='_1ZBFue7VModJTCOy5_yAOu'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='_1ZBFue7VModJTCOy5_yAOu'])[6]</value>
   </webElementProperties>
</WebElementEntity>
