<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubscriptionCancelledSubMessage</name>
   <tag></tag>
   <elementGuidId>d0ef5189-3c84-4c02-a5bc-6c8aae016d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[contains(@class,&quot;sadLogo_thank-you-sub&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[contains(@class,&quot;sadLogo_thank-you-sub&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
