<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shahidIcon</name>
   <tag></tag>
   <elementGuidId>6e1ed725-6cec-4e0a-903c-b0cfa0d0bbf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@alt,&quot;Shahid&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@alt,&quot;Shahid&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
