<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>replayEpisode</name>
   <tag></tag>
   <elementGuidId>a766213b-2b53-47e1-8a27-38ad961fdd15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'LiveMatchesTag_ltr')]//span[text()='Replay'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'LiveMatchesTag_ltr')]//span[text()='Replay'])[1]</value>
   </webElementProperties>
</WebElementEntity>
