<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeThumbnail</name>
   <tag></tag>
   <elementGuidId>414e84c1-f6a3-4490-b5f4-0f6b5075b7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[2]</value>
   </webElementProperties>
</WebElementEntity>
