<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Umniah</name>
   <tag></tag>
   <elementGuidId>f6dd376b-8850-45af-b1a7-437770f3c7f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[@alt='Umniah'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[@alt='Umniah'])</value>
   </webElementProperties>
</WebElementEntity>
