<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>needHelpListNumbers</name>
   <tag></tag>
   <elementGuidId>e891f9f5-e609-46a9-866d-483046200086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'subscriptionNeedHelp_need-help-content__')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'subscriptionNeedHelp_need-help-content__')]</value>
   </webElementProperties>
</WebElementEntity>
