<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assetDescription</name>
   <tag></tag>
   <elementGuidId>804d7bc0-85f2-4d0c-ac34-d9e96562f353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'MediaItem_continueWatchingLabel__')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'MediaItem_continueWatchingLabel__')])[1]</value>
   </webElementProperties>
</WebElementEntity>
