<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>marketingOffersGrid</name>
   <tag></tag>
   <elementGuidId>9f1d8ab3-5f3d-4315-8605-082ca5aee108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='_26nmETSoDyF7gR-5cZ3dXe'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='_26nmETSoDyF7gR-5cZ3dXe'])[2]</value>
   </webElementProperties>
</WebElementEntity>
