<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monthlyPackageNetworkOperatorGrid</name>
   <tag></tag>
   <elementGuidId>5fccc489-7d0a-4090-a84e-63627b9de900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='_26nmETSoDyF7gR-5cZ3dXe'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='_26nmETSoDyF7gR-5cZ3dXe'])[4]</value>
   </webElementProperties>
</WebElementEntity>
