<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsAndConditionsText5</name>
   <tag></tag>
   <elementGuidId>76dca1c4-7610-40f2-b7d1-a8ecdb41e88e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;htmlContaner&quot;]/div/section/div/div/div[2]/ol/li[9]/ul/p[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;htmlContaner&quot;]/div/section/div/div/div[2]/ol/li[9]/ul/p[4]</value>
   </webElementProperties>
</WebElementEntity>
