<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsAndConditionsText</name>
   <tag></tag>
   <elementGuidId>5af65aee-4bd2-473a-99a5-6c09ffb5c683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;htmlContaner&quot;]/div/section/div/div/div[1]/div/h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;htmlContaner&quot;]/div/section/div/div/div[1]/div/h2[1]</value>
   </webElementProperties>
</WebElementEntity>
