<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueFacebookLoginButton</name>
   <tag></tag>
   <elementGuidId>f3770d99-9a5d-4f26-9d7f-66da5c516fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;u_0_4&quot;]/div[2]/div[1]/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;u_0_4&quot;]/div[2]/div[1]/div[1]/button</value>
   </webElementProperties>
</WebElementEntity>
