<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>userprofileText</name>
   <tag></tag>
   <elementGuidId>0d4ddaf9-93f2-4c73-aa56-3530a23446d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div[2]/div/div/div/header/div/div[2]/span/div/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div[2]/div/div/div/header/div/div[2]/span/div/div[2]/div[2]/div/a</value>
   </webElementProperties>
</WebElementEntity>
