<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainContainerBackGroundColor</name>
   <tag></tag>
   <elementGuidId>8270298f-1c3e-4cf1-b4e3-9e24c48275ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;mainContainer&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;mainContainer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
