<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PasswordRecovery</name>
   <tag></tag>
   <elementGuidId>cbe6cbaf-2919-4beb-af2b-660c4e31286e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1[contains(@class,'formTitle_form-title')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1[contains(@class,'formTitle_form-title')]</value>
   </webElementProperties>
</WebElementEntity>
