<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpinnerIcon</name>
   <tag></tag>
   <elementGuidId>3485c2ec-e2c0-4eeb-902e-475199ac844b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@class,'forgetPassword_spinner-icon')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@class,'forgetPassword_spinner-icon')]</value>
   </webElementProperties>
</WebElementEntity>
