<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>privacyPolicyText4</name>
   <tag></tag>
   <elementGuidId>9b94253a-1838-4848-8adf-686297756f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/static-pages/div/div[2]/div/div/div/static-privacy/div/p[10]/strong/u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/static-pages/div/div[2]/div/div/div/static-privacy/div/p[10]/strong/u</value>
   </webElementProperties>
</WebElementEntity>
