<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HDIcons</name>
   <tag></tag>
   <elementGuidId>210c488d-114d-4cf0-84a1-ac1c433685bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@class,'desktopUpsellPlayer_icon__')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@class,'desktopUpsellPlayer_icon__')])[1]</value>
   </webElementProperties>
</WebElementEntity>
