<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>joinNowButton</name>
   <tag></tag>
   <elementGuidId>a4bbde0c-fbf2-4c2d-81d6-fbcd9e6313c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@class,'desktopUpsellPlayer_button__')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@class,'desktopUpsellPlayer_button__')]</value>
   </webElementProperties>
</WebElementEntity>
