<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>offlineIcon</name>
   <tag></tag>
   <elementGuidId>a48c3ac5-8860-44b9-944f-512bb0197c86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@class,'desktopUpsellPlayer_icon__')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@class,'desktopUpsellPlayer_icon__')])[2]</value>
   </webElementProperties>
</WebElementEntity>
