<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>channelIcon</name>
   <tag></tag>
   <elementGuidId>1ad18e5e-8488-4a07-bcb0-6209cd3a2797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@class,'PlayerPlaylistItem_mainContainerStyle')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@class,'PlayerPlaylistItem_mainContainerStyle')])[2]</value>
   </webElementProperties>
</WebElementEntity>
