<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addEmailDescription</name>
   <tag></tag>
   <elementGuidId>fe5269fc-5cf8-41e0-9b2e-7147ea4f4478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'userInformation_linkEmailDisclamer__')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'userInformation_linkEmailDisclamer__')]</value>
   </webElementProperties>
</WebElementEntity>
