<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>genderDropDownButton</name>
   <tag></tag>
   <elementGuidId>b5e91f73-73d6-4317-8d8a-89a5fdd909fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'userInformation_dropdown__2va_T')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'userInformation_dropdown__2va_T')])[1]</value>
   </webElementProperties>
</WebElementEntity>
