<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnterKidsMode</name>
   <tag></tag>
   <elementGuidId>1dc39db0-b992-4817-b9dc-e7bcc239fea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[contains(@class,&quot;SelectProfilePage_profile-kids-mode-text&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[contains(@class,&quot;SelectProfilePage_profile-kids-mode-text&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
