<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeNumberAndDate</name>
   <tag></tag>
   <elementGuidId>d5544a02-b6d4-427a-8f95-7e0b95ac1f0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='_3PzZ1O4sx_1EHQ9KHFYG9u'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='_3PzZ1O4sx_1EHQ9KHFYG9u'])</value>
   </webElementProperties>
</WebElementEntity>
