<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>episodeThumbnail</name>
   <tag></tag>
   <elementGuidId>023761c7-a69e-4856-870f-f31d8f9b9d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='NoMRszwkqIWHwcBlDOLT-'])[3]</value>
   </webElementProperties>
</WebElementEntity>
