<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>foxCinema</name>
   <tag></tag>
   <elementGuidId>46dc65ce-4353-4fdb-9032-f260258268ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/movies/Fox-Cinema?genre=9787')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/movies/Fox-Cinema?genre=9787')]</value>
   </webElementProperties>
</WebElementEntity>
