<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nationalGeographicSpecials</name>
   <tag></tag>
   <elementGuidId>5932a210-f75d-4730-b9a8-202be8ee6464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/movies/Nat-Geo-Movies?genre=9789')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/movies/Nat-Geo-Movies?genre=9789')]</value>
   </webElementProperties>
</WebElementEntity>
