<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nationalGeographic</name>
   <tag></tag>
   <elementGuidId>04e25d81-7372-4429-a26e-e8260d540895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/ar/series/Nat-Geo-Series?genre=9789')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/ar/series/Nat-Geo-Series?genre=9789')]</value>
   </webElementProperties>
</WebElementEntity>
