<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>watchNowHeroBannerButton</name>
   <tag></tag>
   <elementGuidId>0ae9c613-3414-423d-9bc5-98f747d4fa0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[contains(text(),&quot;Regarder&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(text(),&quot;Regarder&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
