<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueButton</name>
   <tag></tag>
   <elementGuidId>10f5227c-79b7-424d-8685-1423ad9917f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'PackageSelectionUpgrade_continueButton__')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'PackageSelectionUpgrade_continueButton__')]</value>
   </webElementProperties>
</WebElementEntity>
