<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>convertTo</name>
   <tag></tag>
   <elementGuidId>0e079472-a708-4c4c-941f-d44eed563212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(@class,&quot;checkoutCard_btn-submit-icon&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(@class,&quot;checkoutCard_btn-submit-icon&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
