<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreditCardImage</name>
   <tag></tag>
   <elementGuidId>8b29a04c-a389-4263-853a-8c6817a2df04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src=&quot;https://static.s3.shahid.mbc.net/widget-images/icons/iconCreditCard.png&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src=&quot;https://static.s3.shahid.mbc.net/widget-images/icons/iconCreditCard.png&quot;]</value>
   </webElementProperties>
</WebElementEntity>
