<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>downgradeToSport</name>
   <tag></tag>
   <elementGuidId>9b098321-c4a8-47f7-9968-4d67aaf948be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,&quot;PackageSelectionUpgrade_selectedButton&quot;)])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,&quot;PackageSelectionUpgrade_selectedButton&quot;)])[3]</value>
   </webElementProperties>
</WebElementEntity>
