<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>downgradeToGIA</name>
   <tag></tag>
   <elementGuidId>a7e75e6d-d9b9-42ba-8925-e4164570b422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,&quot;PackageSelectionUpgrade_selectedButton&quot;)])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,&quot;PackageSelectionUpgrade_selectedButton&quot;)])[2]</value>
   </webElementProperties>
</WebElementEntity>
