<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>downgradeContinueButton</name>
   <tag></tag>
   <elementGuidId>7baee793-43a9-496a-ba82-e474537fdb3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;PackageSelectionUpgrade_continueButton&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;PackageSelectionUpgrade_continueButton&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
