<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobileImage</name>
   <tag></tag>
   <elementGuidId>e8324639-b3bd-4fe2-abb4-6f6ff2e30e86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src=&quot;https://static.s3.shahid.mbc.net/widget-images/icons/iconMobile.png&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src=&quot;https://static.s3.shahid.mbc.net/widget-images/icons/iconMobile.png&quot;]</value>
   </webElementProperties>
</WebElementEntity>
