<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newSubscriptionType</name>
   <tag></tag>
   <elementGuidId>fbf6b6fa-2e27-4e6a-bbbf-cac5f8057c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(@class,'SubscriptionDetails_titleProduct__')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(@class,'SubscriptionDetails_titleProduct__')])[3]</value>
   </webElementProperties>
</WebElementEntity>
