<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscribePlatinumButton</name>
   <tag></tag>
   <elementGuidId>e40e42ce-d45e-4377-8fa7-20b48a2bb19a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'PackageSelectionUpgrade_selectedButton_')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'PackageSelectionUpgrade_selectedButton_')])[3]</value>
   </webElementProperties>
</WebElementEntity>
