<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subscriptionType</name>
   <tag></tag>
   <elementGuidId>52132f27-c24e-4de4-82e4-17ffc7a05b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(@class,'SubscriptionDetails_titleProduct__')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(@class,'SubscriptionDetails_titleProduct__')])[1]</value>
   </webElementProperties>
</WebElementEntity>
