<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TVImage</name>
   <tag></tag>
   <elementGuidId>76748d69-fa11-4fbf-8a1d-bbfeb9b10be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src=&quot;https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/WatchOnTV.png&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src=&quot;https://shahid-static.s3.us-east-1.amazonaws.com/shahid-subscription-config/EV-PRD/WatchOnTV.png&quot;]</value>
   </webElementProperties>
</WebElementEntity>
