<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>voucherButton</name>
   <tag></tag>
   <elementGuidId>6bee9da4-9dd7-4072-91f8-dade588a6961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class,'DefaultSpecialOffer_ctaText__2')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@class,'DefaultSpecialOffer_ctaText__2')]</value>
   </webElementProperties>
</WebElementEntity>
