<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noFeatureAvaiableText</name>
   <tag></tag>
   <elementGuidId>c131cb43-0c4f-42b8-bff5-ccdf04b5bffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'offers_emptyOffersTitle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'offers_emptyOffersTitle')]</value>
   </webElementProperties>
</WebElementEntity>
