<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Orange</name>
   <tag></tag>
   <elementGuidId>4a055379-06ce-43c1-9adf-fd9c7f2aed87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[@alt='Orange'])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[@alt='Orange'])</value>
   </webElementProperties>
</WebElementEntity>
