<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clipThumbnailHomePage</name>
   <tag></tag>
   <elementGuidId>88228fdc-00dd-434e-a548-1f63a8447551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]//div[25]//div[3]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]//div[25]//div[3]//a</value>
   </webElementProperties>
</WebElementEntity>
