<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>favoriteButtonFavPage</name>
   <tag></tag>
   <elementGuidId>324e8a89-9513-4b0f-b7db-4efec3a4150a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]/div/div[1]//div[2]//a/div/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]/div/div[1]//div[2]//a/div/div[1]/img</value>
   </webElementProperties>
</WebElementEntity>
