<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aboutButton</name>
   <tag></tag>
   <elementGuidId>5c2fefb0-a12d-4259-b2f7-111e15423338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appRoot&quot;]//div[1]/div//div[2]/div[1]/div[2]/div[1]//button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appRoot&quot;]//div[1]/div//div[2]/div[1]/div[2]/div[1]//button/img</value>
   </webElementProperties>
</WebElementEntity>
