<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>applicationsFooter</name>
   <tag></tag>
   <elementGuidId>d033df44-c483-4252-a82c-d3e1ac7f7c58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li//h2[contains(text(),'تطبيقات')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li//h2[contains(text(),'تطبيقات')]</value>
   </webElementProperties>
</WebElementEntity>
