<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>homeFooter</name>
   <tag></tag>
   <elementGuidId>72a538ef-6f49-4e76-b4f3-ef3a326356e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li//h2[contains(text(),'الرئيسية')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li//h2[contains(text(),'الرئيسية')]</value>
   </webElementProperties>
</WebElementEntity>
