<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendButton</name>
   <tag></tag>
   <elementGuidId>bbf6b147-243e-4fa2-8e35-947a736112b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button//span[text()='إرسال']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button//span[text()='إرسال']</value>
   </webElementProperties>
</WebElementEntity>
