<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>privacyPolicyPageLink</name>
   <tag></tag>
   <elementGuidId>a94751d1-91de-4cb2-8df3-5a9e2956667e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;htmlContaner&quot;]/div/footer/div/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;htmlContaner&quot;]/div/footer/div/ul/li[7]/a</value>
   </webElementProperties>
</WebElementEntity>
