<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accountSettingsLink</name>
   <tag></tag>
   <elementGuidId>47dacc74-b97e-4e63-9f43-5d526193e145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@href,&quot;/ar/widgets/settings&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@href,&quot;/ar/widgets/settings&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
