<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>androidtvIcon</name>
   <tag></tag>
   <elementGuidId>6b7c1b44-c3c8-407b-be93-eac0a36b503e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@src,'androidtv-devices-icon.svg')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@src,'androidtv-devices-icon.svg')])[1]</value>
   </webElementProperties>
</WebElementEntity>
