<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>devicesIcon</name>
   <tag></tag>
   <elementGuidId>8fddfc47-45c0-4c65-a2d7-63918fa89782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@src,'multi-device-icon.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@src,'multi-device-icon.svg')]</value>
   </webElementProperties>
</WebElementEntity>
