<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IOSIcon</name>
   <tag></tag>
   <elementGuidId>a4cd7ce2-367c-40b7-812c-95696c7165cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@src,'ios-devices-icon.svg')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@src,'ios-devices-icon.svg')])[1]</value>
   </webElementProperties>
</WebElementEntity>
