<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>smartTVIcon</name>
   <tag></tag>
   <elementGuidId>5a2474c8-5ec0-4459-92e4-a184cfe6e36e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//img[contains(@src,'smarttv-devices-icon.svg')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//img[contains(@src,'smarttv-devices-icon.svg')])[1]</value>
   </webElementProperties>
</WebElementEntity>
