<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addProfileAvatar</name>
   <tag></tag>
   <elementGuidId>9d46e3ba-e3a1-4548-a1a8-bfa129f3352a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;AvatarBox_profile-edit-icon&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;AvatarBox_profile-edit-icon&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
