<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kidsPrimaryProfile</name>
   <tag></tag>
   <elementGuidId>ade2faa2-0788-4dcd-9d57-f14b8ea005a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'AvatarBox')]//following::img[contains(@src,'kids')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'AvatarBox')]//following::img[contains(@src,'kids')])[1]</value>
   </webElementProperties>
</WebElementEntity>
