<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>seasonLabel</name>
   <tag></tag>
   <elementGuidId>83e5efd9-7e70-420c-8ef7-fecf0b4f9e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h2[contains(text(),'Saison')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h2[contains(text(),'Saison')])[1]</value>
   </webElementProperties>
</WebElementEntity>
