<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueWatchingIcon</name>
   <tag></tag>
   <elementGuidId>fa86d5ec-ed44-4acc-a139-1da8b58b3d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[contains(@alt,&quot;Watching_widget_header&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[contains(@alt,&quot;Watching_widget_header&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
